spring:
  application:
    name: composer-service
  docker:
    compose:
      enabled: false
server:
  host: ${REMOTE_SERVER_HOST}
  port: 8092
microservice:
  user-api:
    url: http://${server.host}:8093
  project-api:
    url: http://${server.host}:8094
  board-api:
    url: http://${server.host}:8095
  task-api:
    url: http://${server.host}:8096
